# NOTE: When installing, please, update this file with the correct subdomain!

ingress:
  internal:
    annotations: 
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/actions.redirect: "{\"Type\": \"redirect\", \"RedirectConfig\": {\"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
      alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80,\"HTTPS\": 443}]"
      alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=360"
    hosts:
      - path: /renting-api
        serviceName: renting-api-service
        port: 80
      
      - path: /resource-api
        serviceName: resource-api-service
        port: 80
      
      - path: /inventory-api
        serviceName: inventory-api-service
        port: 80

      - path: /clients-api
        serviceName: clients-api-service
        port: 80

      - path: /front-end
        serviceName: front-end-service
        port: 80
